### ISSUE TITLE
[BUG] Can’t Watch or Download Anime

### ISSUE THREAD

**Issue by joiklaa** [SuperMarcus/NineAnimator#102]
![4A39539F-8014-4198-B409-71E7095CC47F](https://user-images.githubusercontent.com/64115969/79933550-0b1a1280-83ec-11ea-9787-c8311de1115c.png)

**Comment by joiklaa** [comment]
Anybody know how to fix this?

**Comment by SuperMarcus** [comment]
Hi @joiklaa 

* Where did you download NineAnimator from
* Which version of NineAnimator are you using? (You can check the app's version and build number in the `Preferences -> About` menu)
* Which source are you currently using for this title?

Our community moderators and other developers are also available in our Discord server: https://discord.gg/dzTVzeW

**Comment by joiklaa** [comment]
Hey, thanks for the help. I downloaded from the Apple App Store and it’s version 1.2 and build 5. The source I’m using is 9anime.ru but I’ve tried the other sources and get the same error.

**Comment by SuperMarcus** [comment]
The App Store version of NineAnimator is outdated. As far as we know, only the gogoanime source works on the App Store release. Please join our Discord server at https://discord.gg/dzTVzeW for more information.

**Comment by uttiya10** [comment]
I would close this issue due to inactivity.
