### ISSUE TITLE
[BUG] Error message when clicking on view episodes (TestFlight version)

### ISSUE THREAD

**Issue by X9Niko** [SuperMarcus/NineAnimator#104]
I have had the Test Flight version of 9animator for a long time and it was working fine. Today I tried to download the AppStore version and when I opened it it didn't work so I uninstalled the AppStore version and downloaded 9animator back from TestFlight. Now in the TestFlight version every time I click on an anime it just says View episodes (before when I clicked on an anime it immediately showed all episodes and I was able to watch them). Now when I click on view episodes I get an error message (I attached a screenshot). I am using the 9anime source.

![03AAB2EC-B2B3-477F-835A-592952142D1A](https://user-images.githubusercontent.com/64311288/80278803-8dab1680-86f9-11ea-995e-4667a4e95bda.png)

 - Device: iPhone 11 Pro
 - OS: 13.3.1
 - Version of 9animator: 1.2.6 (Build 5)

**Comment by uttiya10** [comment]
I dont know how you downloaded the app store since it has been removed. Anyways, since you used the app store version, you have been ip banned on 9anime for one hour. This ban affects you no matter what version of NineAnimator you use. To fix this, please change sources, or just wait 1 hour.
