### ISSUE TITLE
[BUG] AnimeUntima authentication doesn't show up in search

### ISSUE THREAD

**Issue by alet135** [SuperMarcus/NineAnimator#106]
**Describe the bug**
AnimeUntima authentication doesn't show up in search.

**To Reproduce**
* Go to the app
* Click on search (with AnimeUltima)
* After that you will need to verify the app but the (open link) doesn't appear on the screen(notice not the beta one)

**Expected behavior**
When authentication is required by the source during a search, NineAnimator should prompt the user to complete it manually if an automatic resolution is not available.

**Screenshots**
None

**Device (please complete the following information):**
 - Device: Unknown
 - OS: Unknown
 - Version: v1.2-5 (App Store)

**Crash Log**
None

**Additional context**
None

**Comment by alet135** [comment]
iphone 7plus

**Comment by alet135** [comment]
not the beta one the one that is in play store

**Comment by uttiya10** [comment]
App store is very broken, and has been taken down (for now). Please switch to Testflight version. You can ask for a spot on our discord: https://discord.gg/ynfKTj

**Comment by SuperMarcus** [comment]
This issue has been addressed in the repository. We're working on updating the App Store version right now. For more information, please join our Discord server with the link @uttiya10 sent above.
