### ISSUE TITLE
[Feature Request] please add Animehub as one of the sources.

### ISSUE THREAD

**Issue by eobi1976** [SuperMarcus/NineAnimator#123]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by eobi1976** [comment]
It’s a really good website that I use often and it would be great if it could be on NineAnimator as I use it frequently

**Comment by uttiya10** [comment]
Do you know if there is any way to filter out the NSFW titles? Apple is very strict with anything leaning towards the obscenity territories. Having those titles in the app would increase the likelihood of the app getting rejected.

**Comment by Catta1997** [comment]
Seems that there isn't a way to filter NSFW content. Maybe is possible change "Allow NSFW content" to "Allow NSFW content and sources" and add it
