### ISSUE TITLE
[BUG] Search Crash

### ISSUE THREAD

**Issue by Catta1997** [SuperMarcus/NineAnimator#127]
**Describe the bug**
Searching on some sources make app crash
the app Crash whith the sources: 
- AnimeUnity
- 4Anime
- AnimeUltima
- AnimeDao 
- KissAnime

**To Reproduce**
1. Search something on that sources

**Device (please complete the following information):**
 - Device: iPhone 11 Pro
 - OS: iOS 13.5

Tested also with Xcode simulator (same device and iOS version)  with latest commit on GitHub

**Crash Log**
`Xcode report: Fatal error: Unexpectedly found nil while unwrapping an Optional value: file xxxxx/NineAnimator-master/NineAnimator/Utilities/String Operation/String+IntegerRangeSubstring.swift, line 36`
This line is `let range = Range(bounds, in: self)!`
and: `Thread 7: Fatal error: Unexpectedly found nil while unwrapping an Optional value`
**Additional context**
I'll check if this happen also with other iOS versions

**Comment by Catta1997** [comment]
update solve issue

**Comment by uttiya10** [comment]
Cloudflare has changed their challenging scheme for their IUAM mode. This causes NineAnimator to crash. The update introduces a temporary fix by simply forces the user to solve the challenge manually.  Obviously, it would be better to fix the auto-solver in the future.
