### ISSUE TITLE
Too many http redirects

### ISSUE THREAD

**Issue by olsbear** [SuperMarcus/NineAnimator#13]
Error with 9anime source which won’t allow authentification.

**Comment by SuperMarcus** [comment]
Just to make sure. Which version of NineAnimator are you using? Can you goto the preferences panel -> About and check.

**Comment by olsbear** [comment]
Version 1.1, build 2. Was working fine a couple of hours ago but now won’t open authentification screen, just getting a message “error - too many https redirects”

**Comment by SuperMarcus** [comment]
Have you tried accessing the 9anime website directly? Also, maybe a restart of your phone would help.

**Comment by olsbear** [comment]
The website itself was working fine and I’d turned off my phone, deleted and reinstalled the app etc and it still wasn’t working - seems to be working okay now though! Not sure if you did anything or if it fixed itself somehow, but either way thanks 😊
