### ISSUE TITLE
[BUG] PiP crash

### ISSUE THREAD

**Issue by Catta1997** [SuperMarcus/NineAnimator#138]
**STOP!!** Before submitting this bug report, make sure you have filled out the information below and renamed the title of this issue (ex. `[BUG] UrlError when trying to stream an episode on 9ani.app`). The information you provide helps us diagnose the problem and organize our issue tracker.

**Describe the bug**
PiP crash when video re-start
**To Reproduce**
Replace this with the steps to reproduce the behavior:
1. Open a video
2. Start PiP
3. Go to home screen
4. Open the app again
5. Start the same episode

**Expected behavior**
PiP will be disabled an video will continue on full screen

**Screenshots**

**Device:**
Replace the following with the device on which you're experiencing this issue.
 - Device: iPhone 11 Pro (on iOS 14 there is PiP on iPhone too) / iPad 5th gen.
 - OS: 14 beta (don’t know if this issue happen also on stable versions)
 - Version: TestFlight version

**Additional context**
If, during a PiP, you tap on the button on the PiP for disable it, crash will NOT happen

If it is a bug of iOS 14 and not of the app I’m sorry

**Comment by SuperMarcus** [comment]
It'll be great if you can attach a crash log. I haven't installed iOS 14 on my phone and apparently PiP doesn't work in the simulator for some reason.

**Comment by Catta1997** [comment]
> It'll be great if you can attach a crash log. I haven't installed iOS 14 on my phone and apparently PiP doesn't work in the simulator for some reason.

Ok. Also I managed to use PiP on simulator (iPad 7th and iOS 13.5), simulator will crash with  `Thread 1: Exception: "Application tried to present modally an active controller <AVPlayerViewController: 0x7fdeea102a00>."` 
Crash Log: [NineAnimator-2020-06-27-173458.ips.beta.zip](https://github.com/SuperMarcus/NineAnimator/files/4840837/NineAnimator-2020-06-27-173458.ips.beta.zip)
