### ISSUE TITLE
[BUG] Hunter x hunter episodes all turned into the first episode

### ISSUE THREAD

**Issue by raxtpack** [SuperMarcus/NineAnimator#146]
I was watching hunter x hunter for the past few days today I wanted to watch it was at episode 70 I believe and when I clicked onto the anime all the episode turned into the very first one every other anime I have is fine and all the episodes are in order. Using animeultima iOS nineanimator the newest update 1.2.6
![7CCF0C99-9100-45E4-AE61-CDF371EF3089](https://user-images.githubusercontent.com/59778207/87835649-b73c8f80-c85b-11ea-86ac-8490dbf56994.png)

**Comment by SuperMarcus** [comment]
I will be marking this issue as invalid because we cannot reproduce the error with the information provided. Please use the Bug Report template to report issues. When creating new issues, make sure you follow the contents of the template and fill in all fields applicable.

**Comment by uttiya10** [comment]
@SuperMarcus I am able to reproduce this issue using these steps:
1. Switch to animeultima.eu source
2. Search "Hunter X Hunter"
3. Select the second search result (the 2011 edition)

The episode information is the same for every episode.

**Comment by uttiya10** [comment]
![00B1418C-14E2-43C9-A99F-542FE8107C08](https://user-images.githubusercontent.com/56562649/87837768-afccb480-c862-11ea-95cf-36cefeca48df.jpeg)

**Comment by uttiya10** [comment]
@raxtpack Can you please try to see if this issue still exists? It seems to be fixed for me. Thanks

**Comment by raxtpack** [comment]
@uttiya10 @SuperMarcus it is now fixed thank you I will now close this issue <3
