### ISSUE TITLE
[Feature Request] Add PiP support for iPhones with iOS 14

### ISSUE THREAD

**Issue by godly-devotion** [SuperMarcus/NineAnimator#149]
iOS 14 beta introduced the ability for iPhone to show videos in picture in picture (PiP) mode. Please allow PiP option to be enabled on iPhones with iOS 14.

**Comment by uttiya10** [comment]
The app should already be detecting if your device has PiP support:
https://github.com/SuperMarcus/NineAnimator/blob/master/NineAnimator/Controllers/Settings%20Scene/SettingsSceneController.swift#L277

Can you please send a screenshot of the "Preferences" Menu in NineAnimator, specifically the PiP option?

**Comment by godly-devotion** [comment]
Thank you for your quick response! I admit it would have been better to check while running iOS 14 to see if the option was available as I am currently not on the beta. As a user, I assumed this wasn't so because the message underneath the PiP Playback option stated
```
Picture in Picture (PiP) playback is only supported on iPads.
```
Maybe the message can be changed when support is available on iOS devices or reworded to state iOS 14 support?

**Comment by uttiya10** [comment]
Yes I agree that the message is now inaccurate because of iOS 14. We will change it to describe the new requirements. Thanks for bringing it up.
