### ISSUE TITLE
[BUG] 4anime source not viewing episodes

### ISSUE THREAD

**Issue by MegaTareon** [SuperMarcus/NineAnimator#164]
**STOP!!** Before submitting this bug report, make sure you have filled out the information below and renamed the title of this issue (ex. `[BUG] UrlError when trying to stream an episode on 9ani.app`). The information you provide helps us diagnose the problem and organize our issue tracker.

**Describe the bug**
Whenever I go to the 4anime source, I can not view the episodes

**To Reproduce**
1. Click on “select source”
2. Choose “4anime” and click done
3. Choose any anime and click on view episodes

**Expected behavior**
When you click on view episodes with any anime and the 4anime source, it should show the list of anime

**Screenshots**
![CE44E60A-5157-47AC-B457-0015400B461E](https://user-images.githubusercontent.com/69742803/90326266-60a69c00-df54-11ea-8da8-e1ec6394535c.png)

**Device:**
 - Device: [iPhone 6s]
 - OS: [iOS 13.6]
 - Version: [Latest (using AltStore)]

**Crash Log**
```
No crash log
```

**Additional context**
None

**Comment by uttiya10** [comment]
Seems to be a 4anime website issue, since many people are using it now after kissanime died.
![](https://media.discordapp.net/attachments/572811450175848469/744425163390713996/Screen_Shot_2020-08-15_at_10.19.31_PM.png)

**Comment by SuperMarcus** [comment]
Since the source of the issue has been identified as unrelated to NineAnimator, I'll be closing this issue now.
