### ISSUE TITLE
GoGoAnime search 

### ISSUE THREAD

**Issue by Awsomedude** [SuperMarcus/NineAnimator#19]
```swift
if self.totalPages == 0 {
   Log.info("No results found")
   throw NineAnimatorError.searchError("No results found for \"\(self.title)\"")
}
```

Thats a bad way for checking it there is no results since when you search for  ``One punch`` it will be one page with results but it will get caught as no results

https://www3.gogoanime.io/search.html?keyword=One%20Punch&page=1

What you can do is check for ``.items > li`` which should return empty if none 

https://www3.gogoanime.io/search.html?keyword=adasdasd

**Comment by SuperMarcus** [comment]
Thanks
