### ISSUE TITLE
[Source Request] Fastani.net Source Request

### ISSUE THREAD

**Issue by Layendan** [SuperMarcus/NineAnimator#221]
Suggested by Stephanie#1873

[Website Link](fastani.net)

**Note:** This Website Is Protected By *CloudFlare*

**Comment by Moath022** [comment]
I would give the list of all best websites for better quality and different streaming services unlike gogoanime it’s is getting annoying and the quality is dropping. ( kickassanime.rs, tenshi.moe, fastani.net, animeowl.net, kawaiifu.com) 

i would say if these are added iI don’t think anything will make me ever use a browser to watch anime)
