### ISSUE TITLE
WonderfulSubs - Server FA does not display subtitles

### ISSUE THREAD

**Issue by buitim** [SuperMarcus/NineAnimator#23]
Love what you're doing and just wanted to bring this to your attention if it wasn't already. Tried both on my phone (iPhone 8 Plus 12.2) and AppleTV 4K via AirPlay. Video plays just fine but no subtitles are shown. 

Example Case: Kanata no Astra/Astra Lost in Space

Any ideas?

**Comment by Awsomedude** [comment]
It looks like wonderfulsubs has its subtitles separated from video

![Image on video response](http://i.imgur.com/SCOZmoFg.png)

**Comment by SuperMarcus** [comment]
Thanks for letting me know and thanks @Awsomedude for finding out the problem. This will require some changes to the models and will be fixed in the next release. Google Cast users will most likely continue to experience this issue for a period of time.

**Comment by Awsomedude** [comment]
You need to check if is subtitle is separate since not all are like that

![Wonderfulsubs image](https://i.imgur.com/kKRhMYD.png)

**Comment by buitim** [comment]
@Awsomedude is the latter not being fetched from KA? Just a warning, I don't exactly know what I'm doing, but I was looking around and most streams/blobs/whatever you want to call them from FA didn't have any links relating to Rapidvideo.

**Comment by Awsomedude** [comment]
@buitim yeah seems I miss read KA for FA on the servers tab

**Comment by SuperMarcus** [comment]
Closing due to the removal of WonderfulSubs.
