### ISSUE TITLE
[BUG] 4anime.to videos not loading

### ISSUE THREAD

**Issue by stanny4022** [SuperMarcus/NineAnimator#230]
**Describe the bug**
When trying to play an anime found off of the 4anime.to servers, the video is indefinitely loading.

**To Reproduce**
1. Go to "Select Source"
2. Select 4anime.to
3. Locate an anime (ie. Jujutsu Kaisen)
4. Attempt to play an episode.

**Expected behavior**
Expected the episode to finish loading and play with minimum issues.

**Device:**
 - Device: iPhone XS
 - OS: iOS 14.4
 - Version: v1.2.7 build 3

**Additional context**
The video seems to be loading upon starting the episode, but it never finishes loading and ultimately doesn't playback. Had to switch to another source such as gogoanime.tv to watch the episodes.

**Comment by Awsomedude** [comment]
It seems you have an old version of NineAnimator, try downloading the new update.

https://github.com/SuperMarcus/NineAnimator/releases/tag/1.2.7-5
