### ISSUE TITLE
[Feature Request] MacOS Updater

### ISSUE THREAD

**Issue by awsomenes** [SuperMarcus/NineAnimator#231]
Have A updater for nineanimator on macos so that I don’t have to manually download every time

**Comment by Joseos123** [comment]
the most recent commit killed support for intel based macs. IF your mac is based on m1, please take a look at the app Latest from [https://github.com/mangerlahn/Latest](https://github.com/mangerlahn/Latest) and create a PR there.

**Comment by uttiya10** [comment]
@Joseos123 i know im a bit late, i didn't see this comment, but no we are not killing intel mac support. We were trying to remove armv7 support as all ios 12 devices do not use it, but we accidently removed x86_64 support. This will be added back in #233 before a new release is made.
