### ISSUE TITLE
[BUG] Video Delay (audio plays seconds ahead of whats shown on screen), even on internal speakers.

### ISSUE THREAD

**Issue by Joseos123** [SuperMarcus/NineAnimator#259]
**Describe the bug**
There is a noticeable video delay that gets worse the longer you play. It starts to get annoying after 5 minutes or so, as sounds of things happening in the anime do not correspond to what you see.

**To Reproduce**
1. With any downloaded content (have not tried on streamed content due to long buffer times), play an anime for 5-8mins
2. See (and hear) error

**Expected behavior**
Audio to sync with video, as it has with previous builds. Or, for the more common occurrence of the audio being delayed.

**Screenshots**
Not applicable.

**Device:**
 - Device: iPad Pro 11" 1st gen (2018)[A1980]
 - Issue observed on: iPadOS 14.5, 14.5.1, 14.6 and 15.0 DevBeta
 - Version: d88b431 (at time of writing), (also observed on) 220afaf

**Crash Log**
no crashes observed

**Additional context**
Note that this is just to inform the developers of this persisting issue. I know that it is unlikely to be fixed as NA uses stock ios video player to play the video files.

**Additional information**
NA is otherwise working perfectly normally on iPadOS 15.0 Developer beta, build 19A5261w, so thats great!

**Comment by Joseos123** [comment]
should add that the issue goes away after exiting playback and tapping to start playback again.

**Comment by uttiya10** [comment]
By the way you describe the issue, it seems like the issue is with the source that you are using. As you said, we use the stock video player, so I doubt it has any major syncing issues (tho, it is still possible).

May I know the source and server you used to download the videos?

**Comment by Joseos123** [comment]
> May I know the source and server you used to download the videos?

i use 4anime.to
ill try a difference source soon, but i tend to download a whole series before i watch it so ill report back if i find this is an issue with many sources.

the weird thing is that if i dismiss the player or force close the app then return and play the episode the delay is gone for a period of time.

**Comment by uttiya10** [comment]
> i use 4anime.to

I was suspecting it was this source. Many users on our discord have reported similar problems even on the website directly.

I recommend using arrayanime as the source and see if you have any sync issues with that.

**Comment by Joseos123** [comment]
i see. thank you for notifing. the issue dosent occur when connected to airplay so thats what im doing for now. i find 4anime downloads faster and more reliable so yeah.
