### ISSUE TITLE
[Feature Request] Replace with Description

### ISSUE THREAD

**Issue by Swishiie** [SuperMarcus/NineAnimator#261]
Add synopsis per episode, and add an option to have episodes numbered along with the episode names. Also, resolution chooser would be nice but would be understandable if not added.

**Comment by Arch-0** [comment]
Synopsis per episode comes from the source you are currently using, most of them don't have Synopsis for episodes or even episode names for that matter. 

The resolution is also something not achievable with quickTime player, it automatically will choose the best resolution based on your internet connection, it would be achievable through an external video player but as I am not a dev I have no idea if it is in the works or even something they want to implement in the future.

**Comment by Swishiie** [comment]
Ah okay, thanks.
