### ISSUE TITLE
Says I cannot download an episode because i do not have permission to a certain file

### ISSUE THREAD

**Issue by SwavyGravy** [SuperMarcus/NineAnimator#27]
It says I do not have permission to a file named ‘com.marcuszhou.nineanimator.Of-flineContents’ so i cannot download any episodes to watch offline. Help needed

**Comment by SuperMarcus** [comment]
This appears to be another permission related problem. This file should be created and maintained by and only by NineAnimator. I have no idea why this is happening but I'll dig into that.

For the time being you may have to delete and reinstall the app. Make sure to back up your data from the preferences menu.

**Comment by SuperMarcus** [comment]
If you're still having this problem, try backing up your data by exporting history and install the app with TestFlight: [testflight.apple.com/join/SzIVhF6w](https://testflight.apple.com/join/SzIVhF6w)
