### ISSUE TITLE
[BUG] Gogo server not working 

### ISSUE THREAD

**Issue by jimmysofat6864** [SuperMarcus/NineAnimator#270]
**Describe the bug**
Trying to play back video using the Gogo server with gogoanime as a source does not work. Only the other servers show up. Possibly due to gogo using a new URL.

**To Reproduce**
Replace this with the steps to reproduce the behavior:

1. Select gogoanime as source
2. Select any show 
3. Use three dot menu to select gogo server
4. See that video does not play

**Expected behavior**
The video plays back 

**Screenshots**.
![01B6CD1F-3546-4E18-9626-277D2B90014E](https://user-images.githubusercontent.com/69532417/126906330-5b603cd0-04ec-4ab7-8595-7294f9c0ac4f.png)

**Device:**
Replace the following with the device on which you're experiencing this issue.
 - Device: [iPhone 7 Plus]
 - OS: [iOS 14.4.2]
 - Version: [1.2.7-6]

**Comment by uttiya10** [comment]
Can you try downloading the beta version of the app? This should fix Gogo Server:
https://nightly.link/SuperMarcus/NineAnimator/workflows/nightly/master/NineAnimator_Nightly.e0bf4882.iOS.zip

**Comment by jimmysofat6864** [comment]
> Can you try downloading the beta version of the app? This should fix Gogo Server:
> https://nightly.link/SuperMarcus/NineAnimator/workflows/nightly/master/NineAnimator_Nightly.e0bf4882.iOS.zip

I tried installing this on top of my existing installation and it didn’t work. It shows the same message.

**Comment by uttiya10** [comment]
May I know what anime and episode you are trying to watch? Gogo server seems to work for me.

**Comment by jimmysofat6864** [comment]
> May I know what anime and episode you are trying to watch? Gogo server seems to work for me.

Testing Horimiya episode 13. Might be because I need to reinstall the app but at the moment it isn’t working for me.

**Comment by jimmysofat6864** [comment]
I checked again and Gogo server works now. My router was blocking it for
some reason.

**Comment by uttiya10** [comment]
Glad to here the issue has been solved!
