### ISSUE TITLE
[Feature Request] add https://www.animeworld.tv/

### ISSUE THREAD

**Issue by n3otidus** [SuperMarcus/NineAnimator#273]
Hello,

I just discover this app and is amazing, but I wish it has support for animeworld.tv to watch anime sub in Italian.

Thank you very much

**Comment by Catta1997** [comment]
puoi usare AnimeUnity o AnimeSaturn. AnimeUnity aveva un problema ma l'ho risolto, devono solo accettare la PR
--------
You can use AnimeUnity or AnimeSaturn. AnimeUnity had a problem but I solved it, they just have to accept the PR

**Comment by Catta1997** [comment]
@n3otidus I'm working on it, I only have to do the "Featured" section

**Comment by n3otidus** [comment]
> @n3otidus I'm working on it, I only have to do the "Featured" section

Thx soo much!

**Comment by Catta1997** [comment]
> > @n3otidus I'm working on it, I only have to do the "Featured" section
> 
> Thx soo much!

fatto (done)

**Comment by n3otidus** [comment]
> > > @n3otidus I'm working on it, I only have to do the "Featured" section
> > 
> > 
> > Thx soo much!
> 
> fatto (done)

I love you!
