### ISSUE TITLE
[BUG] Gogoanime not working 

### ISSUE THREAD

**Issue by jimmysofat6864** [SuperMarcus/NineAnimator#275]
**Describe the bug**
Any video hosted by gogoanime doesn’t work. 

**To Reproduce**

1. Use gogoanime as host
2. Play any video.
3. Get a SSL error pop up 

**Expected behavior**
Episodes shows and video plays. 

**Screenshots**
![2B41F3B1-027B-4A95-8ECF-4EC53DAEBA67](https://user-images.githubusercontent.com/69532417/129993581-59bfea3a-6426-43b8-b894-afa74afc6057.png)
![5FABD63F-4DA0-4765-8650-78887B930D2A](https://user-images.githubusercontent.com/69532417/129993588-e60656f1-368c-4821-841e-a36276c446f3.png)
![194698D3-BCF1-4FCB-A31A-5BADB02DCDDA](https://user-images.githubusercontent.com/69532417/129993768-10a21b17-a1a5-4958-b409-aba25566a283.png)

**Device:**
Replace the following with the device on which you're experiencing this issue.
 - Device: [iPhone 7 Plus]
 - OS: [iOS 14.4.2]
 - Version: [1.2.7-6]

**Comment by jimmysofat6864** [comment]
Also applies to 4anime.to but 4anime is dead but Gogo isn’t. 
![7135B22B-B1E4-4237-A24E-53E9A40AEDC0](https://user-images.githubusercontent.com/69532417/129993899-4c39a499-571d-4629-8bb0-eb702e40547a.png)

**Comment by uttiya10** [comment]
I cannot reproduce this issue. You already made an issue ticket before and you said the root cause was your router blocking the website. Can you please check if you router is causing this issue as well?

**Comment by jimmysofat6864** [comment]
> I cannot reproduce this issue. You already made an issue ticket before and you said the root cause was your router blocking the website. Can you please check if you router is causing this issue as well?

Yes turns out it was my router again. This app uses a different url than the one I already whitelisted. Also 4ani is dead so when I use that I get the same error.
