### ISSUE TITLE
[BUG] Trying to sign in to MyAnimeList results in '{"status":500,"message":"fetch is not defined"}'

### ISSUE THREAD

**Issue by ShawkMusic** [SuperMarcus/NineAnimator#276]
**Describe the bug**
Trying to sign in to MAL results in '{"status":500,"message":"fetch is not defined"}'

**To Reproduce**
1. Go to Settings/Third-Party Anime Lists
2. Scroll to Myanimelist and tap "Setup MyAnimeList.net"
3. Sign in and tap "Allow"
4. The page is now completely blank and just says '{"status":500,"message":"fetch is not defined"}' OR 50% of the time it will show something else (see screenshots below)

**Expected behavior**
Expected to sign in

**Screenshots**
![0CC0DEDF-48C7-48E7-AF3D-53C3C80FAF2A](https://user-images.githubusercontent.com/48574225/130302807-e6c66806-86f9-4239-92be-d06e7a9261d6.png)
 Sometimes instead of showing the above, it will show whats below instead
![ED6245CA-01D1-4295-B1F4-DC854B5A0D84](https://user-images.githubusercontent.com/48574225/130302881-f6659bbe-1b9d-41da-8d25-296e4a01f6bd.jpeg)
Heres a closer look
![01561CDC-124F-41C6-9722-896B19203E60](https://user-images.githubusercontent.com/48574225/130302898-1147ac84-bca3-438c-a8b0-dbe998ba0670.png)

**Device:**
Replace the following with the device on which you're experiencing this issue.
 - Device: iPad Pro 9.7-inch 1st gen
 - OS: iOS 14.7.1
 - Version: v1.2.7

**Crash Log**
```
If applicable, paste the crash log inside this block.
(Goto Settings.app -> Privacy -> Analytics & Improvements -> Analytics Data to find crash logs)
```

**Additional context**

**Comment by uttiya10** [comment]
I can reproduce this issue. We'll update you once we find the root cause!

**Comment by SuperMarcus** [comment]
This seems to be an issue with our backend server. We have applied a fix and please try again to see if it has been resolved.

**Comment by ShawkMusic** [comment]
Yes, it works now. Thank you!
