### ISSUE TITLE
[Feature Request] Add zoro.to

### ISSUE THREAD

**Issue by xKings** [SuperMarcus/NineAnimator#279]
If possible, can we have zoro.to as a source?

**Comment by ISnackable** [comment]
Hi there, thank you for your request. I've started work on the initial supported for zoro.to: a5b81ae92adc98a31617d8141ada07ad62075cdc
However, there is a issue with adding the external subtitle, so this may take a while to implement.

**Comment by ISnackable** [comment]
Zoro have been added in #297, closing.
