### ISSUE TITLE
[BUG] Buffering anime causes all anime to buffer endlessly

### ISSUE THREAD

**Issue by FlyingPotato82** [SuperMarcus/NineAnimator#281]
**STOP!!** Before submitting this bug report, make sure you have filled out the information below and renamed the title of this issue (ex. `[BUG] UrlError when trying to stream an episode on 9ani.app`). The information you provide helps us diagnose the problem and organize our issue tracker.

**Describe the bug**
When watching something, if I go to a time that isn't buffered yet, it starts buffering endlessly. If I close the episode and open another one, it doesn't load that episode either, just buffers endlessly. 

**To Reproduce**
Replace this with the steps to reproduce the behavior:
1. Open an undownloaded episode
2. Scrub far enough ahead as to cause it to buffer
3. See error

**Expected behavior**
I expected to be able to watch anime

**Screenshots**
![IMG_E7F9E5194B76-1](https://user-images.githubusercontent.com/45513404/132839125-56cf9028-7bea-4ae2-bca7-1413ee31c9ea.jpeg)

**Device:**
Replace the following with the device on which you're experiencing this issue.
 - Device: iPhone 12
 - OS: iOS 14.7.1
 - Version: 9animator version 1.2.7

**Comment by Golden12finch** [comment]
am getting the same issue too, hope they fix it

**Comment by SuperMarcus** [comment]
This issue lacked the context for us to diagnose the problems and was created a while ago, so I'm closing this now. However, if the app still behaves similarly, please create a new issue specifying the source you're using and the server you're streaming on (after searching through existing issues).
