### ISSUE TITLE
[BUG] Anime taking too long to load after skipping

### ISSUE THREAD

**Issue by devraza** [SuperMarcus/NineAnimator#282]
**Describe the bug**
I start playing an Anime, skip a few minutes, and then it takes forever to load. It takes about a minute, which is the same time it takes for me to download the entire episode.

**To Reproduce**
Replace this with the steps to reproduce the behavior:
1. Play Anime
2. Scroll a few minutes 
3. See error

**Expected behavior**
Anime plays with next to no latency

**Device:**
Replace the following with the device on which you're experiencing this issue.
 - Device: iPhone 12 Mini
 - OS: iOS 14.7.1
 - Version: v1.2.7-6

**Comment by 2Cleann** [comment]
Does the same for me hopefully the devs find a fix for it

**Comment by devraza** [comment]
I have found a temporary fix to this issue @2Cleann. Once you start playing a video, skip to a random point in the video and then close the video. This should hopefully reset your point in the video; if not, try again.
