### ISSUE TITLE
[Feature Request] Please make it available on android also i really want to use it and if there is a way to use it on android please tell me, thank you

### ISSUE THREAD

**Issue by Maddyhf** [SuperMarcus/NineAnimator#286]
**STOP!!** Before submitting this feature request, make sure you have filled out the information below and renamed the title of this issue (ex. `[Feature Request] Please add 9ani.app to NineAnimator`).

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Maddyhf** [comment]
[Feature Request] Please make it available on android also i really want to use it and if there is a way to use it on android please tell me, thank you

**Comment by Arch-0** [comment]
This app will never be available on Android.
