### ISSUE TITLE
[BUG] Gogoanime broken servers 

### ISSUE THREAD

**Issue by jimmysofat6864** [SuperMarcus/NineAnimator#293]
**Describe the bug**

Some of the servers such as xstreamcdn, doodstream, and streamsb are broken and give an error. And MP4 upload takes a long time for some reason. Gogoanime is set as source. 

**To Reproduce**
Replace this with the steps to reproduce the behavior:

1. Set Gogoanime as source 
2. Watch any video ex used Komi San 
3. Set source to anything except Gogo Server & MP4 upload
4. Error produced

Also, for some reason MP4 upload is very slow to load for some reason. 

**Expected behavior**
Video plays fine and plays fast. 
**Screenshots**

![FE2A9625-8070-4095-9C32-4AE20FDFCA4A](https://user-images.githubusercontent.com/69532417/142793147-6b091bb7-4748-4a58-9a42-44454d290a03.png)
![8A1334BB-B8D8-4363-B53B-E7416BD8CD43](https://user-images.githubusercontent.com/69532417/142793154-70ec637d-abf4-412f-9625-c71013238039.png)
![8D41C19F-C242-4361-BD25-BDEBA0904B68](https://user-images.githubusercontent.com/69532417/142793158-e4e72a43-e1c2-41c1-b30b-2c188a897123.png)

**Device:**
 - Device: iPhone 7 Plus
 - OS: 14.8
 - Version: 1.2.7-6

**Additional context**
MP4 upload works but is very slow compared to gogo server.

**Comment by ralphieb2t** [comment]
Yeah just seen this. Same issue although I’ve been having trouble with more than just gogo. Also animesaturn and unity I think is effected in the same way I believe as well, and like one other one i can’t remember off-hand that has a different issue. You’re smart to take pics. I’ll remember to do that next time and add them as well. Also it seems the issue someone opened below yours effects a few as well. Have you had any luck with a fix?
