### ISSUE TITLE
[BUG] At least 4 servers totally broken/ others load continuously or immediately prompt u to choose another server(WITH PHOTOS)

### ISSUE THREAD

**Issue by ralphieb2t** [SuperMarcus/NineAnimator#294]
Like the title says there’s one or two servers that don’t even load the titles and I think there’s like one that actually loads the titles but when you click on them they say *no data* tbh the only working server on there rn is “oserver” on animehub and the rest of them that appear to be working, the wheel just spins endlessly. 

p.s. I love this app very much, it is beautifully designed and there’s is no other like it for anime on iOS ever since the other decent ones were shut down(ahem Taiyaki) as some one new to this git, I just wanted to point that out and the fact that- this baby just need a little love, that’s all. A quick run through of sources and servers, a removal of one or 2 and refreshing it with some new ones. It’s a beautiful app, and me being essentially the model of what your end-user base looks like, I’d be happy to help out and test the nightly’s or whatever you need going forward(that is, if you’re in need of more precise information.) just wanted to first drop in, say hi, and give a preliminary outline of the server issue but ya pls let me know! Would love to help any way I can with this now, beautifully aging project!

**Comment by ralphieb2t** [comment]
Took pictures of all broken servers. The only ones to my knowledge, that still work occasionally— is there is 1 on AnimeHub that usually works & GogoAnime sometimes (also I thk monoschinos but there’s not a whole lot in there and the Italian one(but I wouldn’t kno abt that one.)
![DB482BD9-346E-4175-B217-25B9F46046E2](https://user-images.githubusercontent.com/73906926/156607271-3a6a4124-3fa0-439d-98db-db4550f95901.jpeg)
![6CA503D2-4E3E-47E1-A734-DFC2AAAAF66F](https://user-images.githubusercontent.com/73906926/156607283-8293610e-774c-4582-80b8-4e83ffa7e3f9.jpeg)
![8068F933-95F6-483A-AD04-AC2D56F5ABE7](https://user-images.githubusercontent.com/73906926/156607287-69bf6d36-5922-419e-b165-f0f64300705c.jpeg)
![871111BA-F50F-422F-9713-F6AC8F420748](https://user-images.githubusercontent.com/73906926/156607290-c7f4a2b4-3f4f-45ec-9db1-28c300e8f4fc.jpeg)

**Comment by ralphieb2t** [comment]
To reproduce:
Usually you have to either go to search something, or choose the server and a common title and will bounce you to another if not currently working, otherwise will sometimes load continuously(but all the previous photos are from servers that do this immediately upon searching for a title.)

**Comment by Zany-Zachary1** [comment]
Bump. I really want to change to this app but this is holding me back!

**Comment by show37** [comment]
> Bump. I really want to change to this app but this is holding me back!

Please download the latest nightly build. 

https://nightly.link/SuperMarcus/NineAnimator/workflows/nightly/master

1.2.7 release is heavily outdated.

**Comment by ISnackable** [comment]
All of these sources have been shutdown.
