### ISSUE TITLE
I am not able to build the app on xcode

### ISSUE THREAD

**Issue by dheerajbred** [SuperMarcus/NineAnimator#299]
I am newbie to ios/xcode developement. This is what I get when I load the project. I have followed the signing instructions

![image](https://user-images.githubusercontent.com/46578244/150638750-9c39320d-ae57-45ac-bbb7-2fd16819b26d.png)
![image](https://user-images.githubusercontent.com/46578244/150638748-e5c111e6-09c8-4e47-a46f-7708316719f7.png)

Anyone pls do help me out

**Comment by ISnackable** [comment]
Hello @dheerajbred, the issue you're facing is due the missing package `NineAnimatorCommon`. You probably did not pull the `NineAnimatorCommon` submodule when cloning. To pull the submodule into your NineAnimator clone on your local machine, type this command into your terminal in the NineAnimator directory.

```sh
git submodule update --init --recursive
```

If you're still facing this issue after pulling the submodule, I suggest that you reclone the NineAnimator.

```git
git clone --recurse-submodules https://github.com/SuperMarcus/NineAnimator
```

@SuperMarcus  We have to update the installation.md docx regarding this.

**Comment by ISnackable** [comment]
Docs have been updated, closing.
