### ISSUE TITLE
[Feature Request] Allow Notifications permissions for macOS

### ISSUE THREAD

**Issue by Layendan** [SuperMarcus/NineAnimator#300]
**Is your feature request related to a problem? Please describe.**
macOS build of the app does not ask permission to send notifications. Hence, there are no notifications sent.

**Describe the solution you'd like**
Change the plist or other files that would tell MacOS to request notification access.

**Describe alternatives you've considered**
Manually edit the system files to spoof notification access using the terminal.

**Comment by Defaalt** [comment]
Can you please describe how you did it using terminal ?

**Comment by ISnackable** [comment]
@Layendan This is actually a bug, duplicate of #255. It should be resolved in the latest nightly build. Please install the latest nightly build and, report if the issue is resolved. Thanks.
