### ISSUE TITLE
[Feature Request] Make Nine Animator for Android

### ISSUE THREAD

**Issue by Winner875** [SuperMarcus/NineAnimator#305]
Is it possible to make nine Animator for Android I like the app but I don't have an iPhone to use it please try to make it

**Comment by SuperMarcus** [comment]
This project is written with Swift and Apple's proprietary UIKit. And, with the amount of code we have, we cannot port everything to another language/framework. So making NineAnimator available on Android is not going to be possible.

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
This should consequently be closed as not planned rather than complete.
