### ISSUE TITLE
Please add AniMixPlay.to to the sources list

### ISSUE THREAD

**Issue by SpektacleFR** [SuperMarcus/NineAnimator#317]
### Describe your suggested feature

Describe my feature?  You would add AniMixPlay.to to the sources list…

### Other details

It is a scraper, but it is also fast and ad-free.  Also it has Horimiya when none of the others do (it gives an error)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by tyrohellion** [comment]
This would be great. I loved the animixplay extension and when I used aniyomi and use it when I'm on my computer. Big vouch

**Comment by show37** [comment]
It's just a gogo scraper. Use gogoanime instead 🫡

**Comment by KaiDevrim** [comment]
rip animixplay, closed issue
