### ISSUE TITLE
`master` fails to resolve Packages in Xcode

### ISSUE THREAD

**Issue by AndrewSB** [SuperMarcus/NineAnimator#325]
### Steps to reproduce

i've downloaded with `git clone --recurse-submodules https://github.com/SuperMarcus/NineAnimator`. after opening the .xcodeproj, I get the following error 

<img width="1512" alt="Screen Shot 2022-08-15 at 9 35 04 PM" src="https://user-images.githubusercontent.com/3814772/184798877-9ac69a00-fa5d-49ea-ab10-72f582ca982f.png">

### Expected behavior

.

### Actual behavior

it looks related to this issue, but i'm unsure why its cropped up again. the .xcworkspace` also seems to fail, with a different error

### NineAnimator version

n/a

### iOS version

n/a

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuperMarcus** [comment]
Opening the workspace is the way to go. What errors are you getting for that?

**Comment by AndrewSB** [comment]
take it back, the workspace seems to work
