### ISSUE TITLE
[Feature Request] Implement animeworld.tv to the italian anime sources of NineAnimator

### ISSUE THREAD

**Issue by Rayder35** [SuperMarcus/NineAnimator#328]
### Describe your suggested feature

Animeworld.tv is the largest italian anime streaming site, it is way more used and complete than other websites which misses many series.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by show37** [comment]
Join our Discord and download the nightly build. We already have anime world.tv
<img width="277" alt="image" src="https://user-images.githubusercontent.com/44646066/191775525-cb067c8b-fb71-423a-a78b-62a2e2bf7728.png">
