### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by AshKetchum101** [SuperMarcus/NineAnimator#329]
### Steps to reproduce

1. Download NineAnimator iPA with altstore
2. open app
3. try and watch anime

### Expected behavior

The show would start

### Actual behavior

An SSL error occurs
Image: https://ibb.co/ZVyg76x

### NineAnimator version

1.2.7

### iOS version

iOS 16.0.3

### Other details

Getting an SSL error when trying to watch anime

iOS 16.0.3
Sideloaded using AltStore

Image: https://ibb.co/ZVyg76x

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by AshKetchum101** [comment]
By the way this issue occurs with all servers for me.

**Comment by Layendan** [comment]
Try using the nightly version of the app
Download the iOS version of the app here: https://github.com/SuperMarcus/NineAnimator/actions/runs/3120057793
Unzip the file and download the .ipa like you did previously. This should fix the bug you are currently experiencing.

**Comment by AshKetchum101** [comment]
Same thing happens both iOS and pc.
Only one that works in animeworld.tv but I don’t understand italian and

**Comment by AshKetchum101** [comment]
Issue fixed itself on Nightly 1.3.0-2 build after a while. Must’ve been an issue on the sources side itself
