### ISSUE TITLE
App crashes immediately on Iphone Xr (jailbroken)

### ISSUE THREAD

**Issue by bilsp** [SuperMarcus/NineAnimator#331]
### Steps to reproduce

Open the app

### Expected behavior

The app should open

### Actual behavior

The app crashed

### NineAnimator version

1.2.7

### iOS version

Ios 14.3

### Other details

This only happens when my device is in a jailbroken state but i thought i’d report it anyway.
It opens and works normally when it’s not jailbroken.
I’ve tried reinstalling the app but it didn’t open.
I disabled all tweaks and substrate but it didn’t do anything.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by SuperMarcus** [comment]
Seems like this has something to do with the `pspawn_payload-stg2.dylib`, which is likely something related to the jailbreak hooks. So this is unlikely a problem with the app itself.
