### ISSUE TITLE
Did everything stop working all of a sudden?

### ISSUE THREAD

**Issue by ralphieb2t** [SuperMarcus/NineAnimator#334]
### Steps to reproduce

Using either the Nightly or stable ver, search for, or click on any title

### Expected behavior

The title should authenticate and episodes should show

### Actual behavior

Their is an ERROR” NineAnimator cannot understand a response sent by the server: No episodes found for this Anime” msg if you click on a title (regardless of the source). Otherwise if you try searching & clicking on a title, it will come back “error: no data” or something like that. Strangely enough, if I click on “go to website” it authenticates and works fine in another window, it just won’t add the episodes though. Very strange, for the most part I never have any issues with this app and all of a sudden today I am having this issue on 2 different devices. 

### NineAnimator version

1.30 & 1.27

### iOS version

iOS 14

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Sharzzz001** [comment]
Yep. All the sources stopped working. Is it because many of the sources redirect u to a different domain? Like for eg: animepahe.com takes me to animepahe.ru, so is this causing the fetch to fail?
