### ISSUE TITLE
nighly build is expired

### ISSUE THREAD

**Issue by blazklemencic** [SuperMarcus/NineAnimator#347]
### Steps to reproduce

expired

### Expected behavior

not expired

### Actual behavior

expired

### NineAnimator version

latest

### iOS version

ios 16.7.8

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by ibapps39** [comment]
Can you expand on this? I just ran a nightly build via actions, signed via Signulous, and it’s all good even on iOS 18 Dev Beta.

**Comment by blazklemencic** [comment]
after i think 3 months artifacts in actions expire 
![image](https://github.com/user-attachments/assets/90c80b30-97d1-4b07-8177-fa8b5e917062)
thanks for running another it can now be downloaded again😉
