### ISSUE TITLE
Suggestion: Have an active save file in the new file structure/system

### ISSUE THREAD

**Issue by ZhongDev** [SuperMarcus/NineAnimator#35]
Make it so that it is possible to extract a file that has all the metadata of watched anime, settings, etc from the files app and move to a fresh copy of the app. (E.g. if the ignition cert invalidates)

Edit 1: the file is constantly updated so that in the event that you cannot access the app UI, there is still an up to date save file.

Edit 2: this should be possible; I can still access the file structure of the invalided iTorrent app through the files app

**Comment by SuperMarcus** [comment]
Do you mean exposing the entire internal file structure of NineAnimator? Or do you mean adding a function that is constantly exporting backups to an accessible place?

Also, since NineAnimator is on TestFlight now (see the [installation note](https://nineanimator.marcuszhou.com/docs/installation.html#testflight-beta-testing)), you shouldn't have to deal with revoking.

**Comment by ZhongDev** [comment]
Sorry I meant a function that is constantly exporting backups to an accessible place.
This would be useful for those still using ignition, or even in the TestFlight case, if the user doesnt update in 90 days and for whatever reason cannot update, they may extract and save a file with settings and watch progress etc. to move to another device or for future reinstall.

I realize that this is an edge case, but id still like to suggest it :)

**Comment by snowden42** [comment]
@SuperMarcus this issue could be rolled into #113  so maybe close this in favor of that?

**Comment by SuperMarcus** [comment]
I believe the original request is to maintain a copy of the backup file in the app's file structures and make it available to iTunes or the Files app. In case the app is revoked, users will still be able to retrieve the data from the backup files.

IMO this is a good idea, but not many people are going to use or notice this feature. Closing in favor of cloud service integrations.
