### ISSUE TITLE
Unable to watch anime even with a different source selected. 

### ISSUE THREAD

**Issue by sonicdude1012** [SuperMarcus/NineAnimator#38]
![1D96E0BA-684A-4B87-920B-74591033B399](https://user-images.githubusercontent.com/58494480/70103124-94cd6d00-1610-11ea-864a-abfc8fc18088.png)

**Comment by Awsomedude** [comment]
## Try selecting another server by doing the following
![Change server](https://i.imgur.com/H7en9By.png)

**Comment by sonicdude1012** [comment]
Oh okay I will thanks
