### ISSUE TITLE
Suggestion : add Italian server

### ISSUE THREAD

**Issue by Catta1997** [SuperMarcus/NineAnimator#40]
Can you add https://animeunity.it/ server? 🙏🏻

**Comment by SuperMarcus** [comment]
Is this website only accessible from certain countries? Cloudflare is giving me a 1020 error.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/7273813/73183903-93d52b00-40e9-11ea-8a84-a2d93225ab34.png">

**Comment by Catta1997** [comment]
idk, I have no error. Maybe is only accessible from Italy

**Comment by Catta1997** [comment]
so you can't do it? If I will do it and do a "pull request" will you add it?

**Comment by SuperMarcus** [comment]
Of course! Would you also be interested in helping to [translate](https://translate.9ani.app) the app to Italian?

**Comment by Catta1997** [comment]
of course!!

**Comment by Catta1997** [comment]
uploaded a "Pull Request" for AnimeUnity server
