### ISSUE TITLE
suggestion: add catalyst support

### ISSUE THREAD

**Issue by Catta1997** [SuperMarcus/NineAnimator#41]

**Comment by SuperMarcus** [comment]
Tbh I'm eager to see NineAnimator working on macOS as well. The only problem is with the dependency manager that NineAnimator is using. In order for Catalyst to work all the dependencies have to be packed with the new `XCFramework` format, which Carthage doesn't support generating yet (see Carthage/Carthage#2799).

As soon as `XCFramework` generation support for Carthage drops I'll work on the Catalyst support for NineAnimator.

**Comment by FaizanDurrani** [comment]
I built a Catalyst version of the app here https://github.com/FaizanDurrani/NineAnimator/releases/tag/1.2.6-Mac

It uses Swift Package Manager to resolve the dependencies. So, completely removed Carthage.

**Comment by Catta1997** [comment]
@SuperMarcus any update?

**Comment by SuperMarcus** [comment]
I haven't got many chances to work on this. Replacing Carthage with SPM is certainly something worth considering, especially since the mainstream Carthage likely won't get xcframework support anytime soon.

I've already created a [spm branch](https://github.com/SuperMarcus/NineAnimator/tree/spm) in the repository for experimentations. I am probably not going to merge #75, but it's a good reference for how things can be done.

**Comment by SuperMarcus** [comment]
So I spent a little time on Swift PM this weekend (check out the [spm branch](https://github.com/SuperMarcus/NineAnimator/tree/spm)) and got Catalyst working. Here's a [notorized build (v1.2.6-11)](https://github.com/SuperMarcus/NineAnimator/files/4810065/NineAnimator_macCatalyst_1.2.6_Build_11.zip) if you're interested in trying it out. Of course, the UI still looks very much like an iOS app, and we'll need to do a little redesign on this.

![NineAnimator macCatalyst](https://user-images.githubusercontent.com/7273813/85232686-cea86a00-b3ce-11ea-8350-d653273cbe93.png)
* [NineAnimator_macCatalyst_1.2.6_Build_11](https://github.com/SuperMarcus/NineAnimator/files/4810065/NineAnimator_macCatalyst_1.2.6_Build_11.zip)

**Comment by Catta1997** [comment]
Great thanks! I'm also testing on iOS 14 and works perfectly

**Comment by Catta1997** [comment]
@SuperMarcus with macOS Big Sur (Beta) and the new Xcode according with Apple's site:
> Native Mac apps built with Mac Catalyst can share code with your iPad apps, and you can add more features just for Mac. In macOS Big Sur, you can create even more powerful versions of your apps and take advantage of every pixel on the screen by running them at native Mac resolution. Apps built with Mac Catalyst can now be fully controlled using just the keyboard, access more iOS frameworks, and take advantage of the all-new look of macOS Big Sur. There’s never been a better time to turn your iPad app into a powerful Mac app.

**Comment by SuperMarcus** [comment]
I've merged the spm branch into master. We'll continue to work on macCatalyst related tasks in the master branch.

Closing this issue.
