### ISSUE TITLE
Pinching inwards on an open episode will not close playback like pressing “X” does.

### ISSUE THREAD

**Issue by Bonnette2020011** [SuperMarcus/NineAnimator#42]

**Comment by SuperMarcus** [comment]
Thank you for reporting this issue. What do you mean by "like pressing 'X' does"? Can you explain it a little more about what happened after you pinch inwards?

**Comment by Bonnette2020011** [comment]
iOS’s native video player uses an “X” in the upper-left-hand corner to close the stream of video and its playback. It also allows “pinching” on the screen to close, but in that case, the video stream isn’t closing properly and you still hear it being played in the background; opening it again will bring up playback like the stream was never even closed.

For reference, I’m using an iPad 6 running the latest consumer-release iOS.
