### ISSUE TITLE
Suggestion: no Home permission

### ISSUE THREAD

**Issue by Catta1997** [SuperMarcus/NineAnimator#43]
if I go to preference --> home and hit "no" on the permission request the next time I will not have an error if I press "starts" or "ends". Error could be useful if I not remember to refused the request on past time

**Comment by SuperMarcus** [comment]
Thanks for the suggestion! I've implemented this for devices running iOS 13 or higher (since there's no way to tell from the app if the permission is being given or not before iOS 13).
