### ISSUE TITLE
Tracking service issue

### ISSUE THREAD

**Issue by Spidey45** [SuperMarcus/NineAnimator#45]
Tracking with Anilist.co is not working. MAL and Kitsu works fine but it’s not working with anilist.co.

**Comment by SuperMarcus** [comment]
Do you mean NineAnimator doesn't update the statuses and progresses on Anilist? Also, what version of NineAnimator are you using? What's your OS version?

**Comment by Spidey45** [comment]
1)yes (using mal for now)
2)latest 1.2 build 3 which is available on testflight.
3) ios 13.3 iphone 11

**Comment by SuperMarcus** [comment]
This issue should be fixed in 9691b14, and will be shipped with the next release.
