### ISSUE TITLE
NineAnimator issues

### ISSUE THREAD

**Issue by raxtpack** [SuperMarcus/NineAnimator#47]
I’m having some problems with the app. Everytime I click on an anime for example highschool dxd, it takes forever to load the episodes and than says “there is something wrong with the URL” and sometimes also says cannot gather information or something like that. I am using the source anime ultima. If this is a bug can you please fix this ASAP or if this is a bug on my part if you will be able to tel me what’s wrong and how I can fix it I will appreciate that :3

**Comment by raxtpack** [comment]
Never mind it’s working but imma keep this here just in case I did nothing it randomly works

**Comment by SuperMarcus** [comment]
Usually, if the app shows a repeated error, try clearing the caches from the Preferences panel.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
