### ISSUE TITLE
[Feature Request] Add descriptions to each episodes 

### ISSUE THREAD

**Issue by uttiya10** [SuperMarcus/NineAnimator#49]
Each episode in a anime series should have a button to show the description. This will make finding certain clips from an anime much easier to find. You might be able to use Crunchyroll as they have descriptions for many animes, publicly available.

**Comment by SuperMarcus** [comment]
The challenge for implementing this feature, similar to that with the tracking services, is that there's no way to match the anime and episodes automatically and accurately to those on Crunchyroll and other sources. So if the matching went wrong you might end up with the description and screenshot of one episode being shown with another episode of a different anime.

**Comment by uttiya10** [comment]
I just did some research, and here is what I found. If anything is wrong, please correct me!
Currently, episodes don't show thumbnails, titles, or description on your app.
The app is getting list of episodes from 9anime, kissanime, etc.
However, the app is getting anime details like synopsis and ratings from MyAnimeList, so I'm assuming that the app is matching the two sources together already.
If this is true, isn't it possible to extract the title, and thumbnail from MAL and add it to the list of episodes? Unfortunately, MAL does not provide episode descriptions.

**Comment by SuperMarcus** [comment]
Yes, you're right. The app does attempt to match anime on different websites with tracking services (MyAnimeList, Anilist, Kitsu, and Simkl). However, the app doesn't always make the right choice -- it might match, for example, Konosuba 2 to Konosuba. If we rely on this information (as I said in the first comment) we will likely end up showing the users the wrong descriptions and screenshots.

**Comment by uttiya10** [comment]
Sorry for the late reply, life’s been busy. Unfortunately, I cannot find an accurate way to match the two websites, therefore Im closing this issue and will re-open if I discover anything new!
