### ISSUE TITLE
[Feature Request] Add ability to clear items from search history

### ISSUE THREAD

**Issue by uttiya10** [SuperMarcus/NineAnimator#51]
Swiping left on an item should delete it from the search history, similar to the youtube app. A clear all search history button would also be nice!

**Comment by SuperMarcus** [comment]
NineAnimator doesn't store your search history at the moment. All the items in the Search tab are fetched from your recently visited anime list. But I guess it's possible to implement a switch in the Preferences menu that allows you to disable these items.

**Comment by uttiya10** [comment]
When you're talking about "recently visited anime list", are you talking about the list that appears when you click the "Recents" button in the Library tab?

**Comment by SuperMarcus** [comment]
> the list that appears when you click the "Recents" button in the Library tab?

Yep, as defined here: https://github.com/SuperMarcus/NineAnimator/blob/772a120a3422b0d879a9037254291bf5ec2b11d1/NineAnimator/Models/User/User%2BHistory.swift#L23-L35
