### ISSUE TITLE
Free developer account not supported in newest builds

### ISSUE THREAD

**Issue by 298y** [SuperMarcus/NineAnimator#53]
Hi, just wanted to let you know that the newest two builds use associated domains and thus require a paid developer account. It would be great if you still made it possible to build it with the free account :)
Thanks

**Comment by SuperMarcus** [comment]
I believe it would still be possible to build with a free account if you disable the HomeKit capability and remove the associated domains. Would you mind testing that out?

**Comment by 298y** [comment]
Hi, I wanted to try that but actually i can’t get the app to reinstall correctly on both 1.2.5 and 1.2.3 now that the first week expired - it crashes on the loading screen or keeps loading endlessly - it only happens on real devices, the simulator works fine and it used to work for a week. I tried changing the bundle indentifier and the version id but it still does that although the certificate apears to be renewed

**Comment by SuperMarcus** [comment]
Just as a follow-up, were you able to get it to work? What was the error Xcode was giving you?

**Comment by Catta1997** [comment]
the problem is `Your development team, "xxxxxxx", does not support the Associated Domains capability.`. If I remove Associated Domains from the project the app crash on start
