### ISSUE TITLE
[Wonderful Subs] Not working

### ISSUE THREAD

**Issue by DaneshIV** [SuperMarcus/NineAnimator#55]
![25B318B5-D278-46EC-AF10-43EE419472A5](https://user-images.githubusercontent.com/37767781/74921400-adc40e00-5408-11ea-8f62-f222660687a0.png)

**Comment by Awsomedude** [comment]
**wonderfulsubs is down for me**

![image](https://i.imgur.com/g8an0iU.png)

**Comment by SuperMarcus** [comment]
It seems like WonderfulSubs is working now. Try to swipe down on the Featured page. If that didn't work, go to the Preferences page, scroll to the bottom, and tap on Clear Cache.

Please let me know if you're still having problems.

**Comment by geekygabe** [comment]
yeah mine isn’t working either, hopefully this helps

**Comment by GalacticNUB** [comment]
Same problem😬

**Comment by SuperMarcus** [comment]
@geekygabe @GalacticNUB are you guys receiving this error when you’re using WonderfulSubs as well?

**Comment by geekygabe** [comment]
@SuperMarcus i was actually on getting it on 9anime but wonderful subs was fine for me.

**Comment by SuperMarcus** [comment]
@geekygabe We're currently experiencing issues with 9anime (see #58)

**Comment by uttiya10** [comment]
Wonderful subs seems to working fine. Im able to see featured anime, search up anime, BUT im cant watch some anime. For example, searching up Classroom Assassination, and trying to watch using any server, results in “This episode is not available on this server” error. However, watching the episode on directly on the website works perfectly. 
![4BCD1E99-BEAD-47F6-B05D-18DCBC2E66D1](https://user-images.githubusercontent.com/56562649/75568299-00ad4f00-5a21-11ea-9423-2f945c8c083b.png)

**Comment by SuperMarcus** [comment]
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/7273813/75636984-58021980-5bf1-11ea-80e1-a3f232b09e7b.png">

@uttiya10 I've tried [the episode in your screenshot](https://www.wonderfulsubs.com/watch/ansatsukyoushitsutv?s=ka&t=subs&ss=0&e=0) on the KA server and it doesn't seem to be working on WonderfulSubs' website as well. I've tried a couple of other anime and episodes on different servers and they all reflect what the source website shows.

Can you open up your browser's Developer Tools, go to the Network page, refresh the webpage with the debugger on, and filter out the `stream` requests?

If you're using Chrome, it should be something similar to this:

<img width="1074" alt="image" src="https://user-images.githubusercontent.com/7273813/75637146-79afd080-5bf2-11ea-9034-1c53db19e59e.png">

**Comment by uttiya10** [comment]
![image](https://user-images.githubusercontent.com/56562649/75642197-ad95f080-5c08-11ea-9f4b-ea7fb27c6f65.png)
@SuperMarcus Man I am BLIND. I selected the anime on the right (broken), using NineAnimator. However, I selected the anime on the left (not broken), using the web browser. I didn't realize that I selected two different anime's, so I thought the app was broken. My bad!!

**Comment by SuperMarcus** [comment]
@uttiya10 no worries. Closing this issue for now.
