### ISSUE TITLE
[9anime] JSON Serialization Error: Data isn't in the correct format

### ISSUE THREAD

**Issue by GalacticNUB** [SuperMarcus/NineAnimator#58]
![60E5C046-F908-4D76-A53A-1D6F0BD9D9F6](https://user-images.githubusercontent.com/47874505/75100495-b3019400-5593-11ea-9dfd-d58f63525425.png)

So I’m in the 9anime.ru server, And for some reason I’m getting this error on the picture below when I try to watch Anime, if you could help me with this that would be amazing! Thank you!

**Comment by uttiya10** [comment]
This is not an issue with NineAnimator! 9anime has started to IP ban people who are using this app for some reason. While this issue is being fixed, for now just use another server like 4anime or gogoanime.

**Comment by uttiya10** [comment]
I also recommend joining the discord server as there are also many people on it, so you will get a faster response. Heres the link: https://discord.gg/kJ36ux

**Comment by stringedcode** [comment]
There is a problem with changing the site to it’s like all of them are having the same problem even when I tried gogo anime it still said something about JSON what ever that is.

**Comment by uttiya10** [comment]
Join the discord and read the pinned messages in the general chat. It has the solution to this

**Comment by uttiya10** [comment]
Heres the discord link: https://discord.gg/64D5GkK

**Comment by SuperMarcus** [comment]
For anyone who's still seeing this error: this issue has been addressed in the latest version and builds of NineAnimator, which is available through the TestFlight Beta Program. App Store users may still experience this issue. Please join our Discord server for more information.
