### ISSUE TITLE
Darkmode into 'true black'

### ISSUE THREAD

**Issue by show37** [SuperMarcus/NineAnimator#6]
Add a third or replace the current 'greyish black' theme with a 'true black' one to save more battery on OLED devices.

**Comment by ApolloZhu** [comment]
Have you tried to turn on Smart Invert?

**Comment by show37** [comment]
> 
> 
> Have you tried to turn on Smart Invert? That should switch all white pixels to black except pictures and videos remain their original color.

Yep, but I don't like it. Waiting for JB support on A12 devices (unc0ver) to do it myself (if not possible).

**Comment by SuperMarcus** [comment]
I experimented with the completely back theme a little bit and frankly I feel like there is just too much contrast between the pictures/texts and the background. The original grayish tint kinds of make the interface looks smoother.

| Featured Page | Recents Page |
| -------------- | --------------|
| ![img_0805](https://user-images.githubusercontent.com/7273813/53690264-50d1d280-3d35-11e9-9580-3720b0e6860c.PNG) | ![img_0806](https://user-images.githubusercontent.com/7273813/53690268-562f1d00-3d35-11e9-8aae-ada52ee667b0.PNG) |

I will be putting this issue on hold right now, but I am willing to hear more opinions about it.

**Comment by show37** [comment]
Maybe change the font color to ![#C0A8F5](https://placehold.it/15/C0A8F5/000000?text=+) `#C0A8F5`

**Comment by PlanetAaron** [comment]
> I experimented with the completely back theme a little bit and frankly I feel like there is just too much contrast between the pictures/texts and the background. The original grayish tint kinds of make the interface looks smoother.
> 
> Featured Page	Recents Page
> ![img_0805](https://user-images.githubusercontent.com/7273813/53690264-50d1d280-3d35-11e9-9580-3720b0e6860c.PNG)	![img_0806](https://user-images.githubusercontent.com/7273813/53690268-562f1d00-3d35-11e9-8aae-ada52ee667b0.PNG)
> I will be putting this issue on hold right now, but I am willing to hear more opinions about it.

I think it looks really nice personally. But not everyone will agree. Maybe adding an option to change tint color as well could help people who don’t like the default.

**Comment by uttiya10** [comment]
This issue fits under #60 so i recommend closing this issue since its very similar to that one.

**Comment by SuperMarcus** [comment]
Closing in favor of #60.
