### ISSUE TITLE
[BUG] Losing Reference to Alamofire Session

### ISSUE THREAD

**Issue by raxtpack** [SuperMarcus/NineAnimator#61]
Having nineanimator errors
It’s takes a while to load the anime’s information and it gives this error don’t know what’s its asking clear cache and all but still doesn’t work
![24AD3A0E-2032-4842-8439-9DADAC820012](https://user-images.githubusercontent.com/59778207/76283417-ec632080-6270-11ea-993a-ed0c587506e8.png)

**Comment by SuperMarcus** [comment]
@raxtpack just to make sure, you’re on the latest version 1.2.6 build 1 or 2, right?

**Comment by raxtpack** [comment]
Using Version 1.2.6 
Build 3  
Using animeultrima 
I did check the sources website it was down than it worked could be because of that not sure but the app was working just fine and I closed it at 9:36 am yesterday Monday couple hours I say 12 I went to check on a episode clicked on the anime took forever to load and that error appeared and doesn’t still work at 10:29 Tuesday night. Not sure why it’s doing it maybe the source is down or broken could be I messed something up like didn’t close the app properly I did delete and reinstall. But no luck

**Comment by raxtpack** [comment]
I think I may have found the problem
I believe it’s the source animeultima It seems to only happen with that source. Animeultima.eu was down for a week or so now if you go to the website animeultima.eu it brings you to the other animeultima.

**Comment by uttiya10** [comment]
Hello @raxtpack can you update to build 4 and see if the problem has been fixed. If it is, please close this issue. Thanks!!

**Comment by raxtpack** [comment]
I’ve have updated to build 4 the error no longer appears but the anime’s that we’re in my subscription they won’t load one time it loaded and when I tried to click on a episode it gave 404 error but other than that everything works the anime I search in the search tab works and loads the episodes and allows me to watch it

**Comment by raxtpack** [comment]
Works great thanks had some problems but they have been covered <3
