### ISSUE TITLE
[BUG] Downloads restart when reaching 99.9%

### ISSUE THREAD

**Issue by Tankid** [SuperMarcus/NineAnimator#62]
**Describe the bug**
Every time I try to download an episode, when it reaches 99.9% it restarts from 0% and so on again and again.
I tried different sources and servers but same issue

Version 1.2.6 
BUILD 1

**Comment by Awsomedude** [comment]
From where was the app installed? Some people had problems with downloading when they had the app installed with appcake.

**Comment by Tankid** [comment]
from buildstore

**Comment by Awsomedude** [comment]
I recommend installing the app through TestFlight

**Comment by Tankid** [comment]
Is there a difference between this and appstore and testflight versions?

**Comment by Awsomedude** [comment]
The appstore app is currently not being updated, while the testflight has the current update

**Comment by Awsomedude** [comment]
Any third party signings you will run to permission issues on how the app is signed

**Comment by Tankid** [comment]
Ah, ok thanks
Since the beta is full, I'll stick with the buildstore version for now

**Comment by Amzd** [comment]
This still happens on latest version installed using ReProvision.
