### ISSUE TITLE
[BUG] KissAnime Error: "This episode is not available on the selected server"

### ISSUE THREAD

**Issue by BigPinhead** [SuperMarcus/NineAnimator#64]
HydraX isn’t working for kissanime, and sometimes nearly all servers won’t work, when I watched yuuna and the hot springs it only worked with hydraX, every other server said there was an error.

**Comment by SuperMarcus** [comment]
Are you getting errors like:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/7273813/77003146-2ac4a380-6933-11ea-8106-c9e2040eff85.png">

The thing with Kissanime is that they don't tell you which episodes exist on what server by just accessing one page. And it seems like different episodes can be streamed from an entirely different list of servers. To show the list of available servers, NineAnimator will either have to request all the episode pages (which is unpractical) or pick an episode, request the list of servers for that episode, and generalize that list to every other episodes from the same anime (current solution).

**Comment by uttiya10** [comment]
One potential solution is have the user select an episode to watch, then show a dialog, asking them to select a server for that episode.

**Comment by SuperMarcus** [comment]
@uttiya10 on a second thought, you're right. NineAnimator does have something built-in for situations like this: https://github.com/SuperMarcus/NineAnimator/blob/d98278dbbbf7d98eec2f6e552321665d3dca6974/NineAnimator/Utilities/Error.swift#L290-L325

This *alternative server recommendation* function has already been implemented for [AnimeDao](https://github.com/SuperMarcus/NineAnimator/blob/d98278dbbbf7d98eec2f6e552321665d3dca6974/NineAnimator/Models/Anime%20Source/animedao.com/AnimeDao%2BEpisode.swift#L72-L89). I'll start working on the UIs in `AnimeViewController` and implementations for KissAnime tomorrow.

**Comment by SuperMarcus** [comment]
NineAnimator now presents a dialog if the selected episode is not available on the current server.
