### ISSUE TITLE
[BUG] Animepahe "This episode does not exists"

### ISSUE THREAD

**Issue by Uryl** [SuperMarcus/NineAnimator#65]
- Device: [iPhone 7 Plus]
 - OS: [iOS 13.3]
 - Version: [1.2.6 (3)]

Unable to stream episodes 481-502 of 
“Detective Conan” on source Animephae, I’ve made sure if all these episodes were working or not finally concluding that all twenty-two episodes do not stream.

I’m unsure if this is only effecting these episodes, it’s possible other anime might be experiencing the same issue for that matter.

p.s 
The episodes 481-502 are able to stream on Animephae’s website.

![B4373D6E-E521-4C6D-B28D-CF3427E8E4EA](https://user-images.githubusercontent.com/62167286/76676603-3d398880-6593-11ea-8dc9-79271b163b95.jpeg)
![46625154-D924-489F-B0FA-CB4A168B9210](https://user-images.githubusercontent.com/62167286/76676604-3f034c00-6593-11ea-8a36-f28566e12340.jpeg)

**Comment by Awsomedude** [comment]
@SuperMarcus I believe the problem has to do with this code here:

https://github.com/SuperMarcus/NineAnimator/blob/master/NineAnimator/Models/Anime%20Source/animepahe.com/AnimePahe%2BAnime.swift#L101-L104

I printed the results out and I got 

``(episodeNumber: 481, page: 17), (episodeNumber: 482, page: 17), (episodeNumber: 483, page: 17), (episodeNumber: 484, page: 17), (episodeNumber: 485, page: 17), (episodeNumber: 486, page: 17), (episodeNumber: 487, page: 17), (episodeNumber: 488, page: 17), (episodeNumber: 489, page: 17), (episodeNumber: 490, page: 17), (episodeNumber: 491, page: 17), (episodeNumber: 492, page: 17), (episodeNumber: 493, page: 17), (episodeNumber: 494, page: 17), (episodeNumber: 495, page: 17), (episodeNumber: 496, page: 17), (episodeNumber: 497, page: 17), (episodeNumber: 498, page: 17), (episodeNumber: 499, page: 17), (episodeNumber: 500, page: 17), (episodeNumber: 501, page: 17), (episodeNumber: 502, page: 17),``

Which it saying the episode is on page 17, but when you go their site its on page 16 (`sorting asc`)

https://animepahe.com/api?m=release&id=3&l=30&sort=episode_asc&page=16

**Also some episodes come together like 481 and 482**

**Comment by SuperMarcus** [comment]
Animepahe should work again with ed93ab4.
