### ISSUE TITLE
Apple TV App

### ISSUE THREAD

**Issue by jennataiga** [SuperMarcus/NineAnimator#67]
It would be really nice if you can make a apple tv app, most people like to watch animes on tv rather than on iPhone. 

P.S. NineAnimator UX/UI + user experience is really next level.

**Comment by SuperMarcus** [comment]
Thanks! This issue has been brought up before in #44. TL'DR, I don't own an AppleTV so I won't be able to test the app. If somebody can submit a PR for tvOS support, I will certainly consider merging it.
