### ISSUE TITLE
[BUG] every time I try to search for a anime on kissanime.ru/[source] nothing shows up

### ISSUE THREAD

**Issue by chax350** [SuperMarcus/NineAnimator#71]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**
 - Device: [e.g. iPhone Xs Max]
 - OS: [e.g. iOS 13.3]
 - Version: [e.g. v1.2-3 or commit hash]

**Crash Log**
```
If applicable, paste the crash log inside this block.
(Goto Settings.app -> Privacy -> Analytics & Improvements -> Analytics Data to find crash logs)
```

**Additional context**

**Comment by uttiya10** [comment]
Doesn’t seems like a bug with NineAnimator. The kissanime website is under maintenance.
![B44CC0E4-7C4A-4AA1-97A0-FA76A8A069DF](https://user-images.githubusercontent.com/56562649/77498422-fadf3980-6e25-11ea-983e-5f8d0ef5e539.png)

**Comment by uttiya10** [comment]
Looks like kissanime is fixed now. Please test for yourself and close the bug report if everything is working for you @chax350
