### ISSUE TITLE
Please make a new release on GitHub 

### ISSUE THREAD

**Issue by uttiya10** [SuperMarcus/NineAnimator#73]
Some people on discord are using the .ipa files on github. However, the current release is build 1, while TestFlight has build 3, so its getting kinda old. Can you make a new release?

**Comment by SuperMarcus** [comment]
Both version 1.2.6 build 2 and 3 didn't introduce anything ground-breaking or fix anything critical. In fact, the only reason that build 3 was released was to fix a bug introduced by build 2.

I'm planning to make a new release this weekend with the commits that have been accumulated to this point. So please just wait a little longer :wink:

**Comment by uttiya10** [comment]
Closing this issue since you released Build 4!!!!
