### ISSUE TITLE
[BUG] 4anime Error: "There is something wrong with the url"

### ISSUE THREAD

**Issue by Kylixer** [SuperMarcus/NineAnimator#83]
**Describe the bug**
For some reason, whenever I tried to watch anything while I was using the source 4anime.to, I got a message saying “Error: There is something wrong with the url”. I never had a problem like this before and it started today about 2 hours ago. Before that, it was working perfectly fine.

**Screenshots**
![DFDC5975-9D2F-4389-8EE4-C0E934D79380](https://user-images.githubusercontent.com/62918500/77978255-91e93d00-72cf-11ea-81e9-15364adedb1d.png)

**Device**
 - Device: Iphone 7
 - OS: iOS 13.3.1

**Comment by uttiya10** [comment]
Fixed in commit 3aff9a0
