### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by turtle696966969696** [SuperMarcus/NineAnimator#84]
There seems to be an error that isnt letting me download or watch shows

**Comment by uttiya10** [comment]
Please join the discord server and tell us your issue there: https://discord.gg/3NDHpW

**Comment by SuperMarcus** [comment]
I will close this issue now since it's not clear what the error is. Please use the [Bug Report](https://github.com/SuperMarcus/NineAnimator/issues/new?assignees=SuperMarcus&labels=bug&template=bug-report.md&title=%5BBUG%5D) template when reporting an issue related to NineAnimator.
