### ISSUE TITLE
[Feature Request] Add "Show Information" site

### ISSUE THREAD

**Issue by Catta1997** [SuperMarcus/NineAnimator#86]
is possible to add a "show information" (the one with character, rating, synopsis) using a site that not support list (`https://www.animeclick.it/`) but report only the information of an anime?

**Comment by uttiya10** [comment]
You mean an ability to manually search up anime on MAL? 
Since that’s where the anime info is from. 
It would be hard to automatically search MAL using any website, since every website has a different design, so we wouldn’t know where the title of the anime would be located.

**Comment by Catta1997** [comment]
not exactly, I only want to add on my own a new source in "preferred source" but the source that i want to add does not support the list but only show information. but i not understand reading the source code how MAL link the anime and how to return the information. Is it not possible/very difficult?

**Comment by uttiya10** [comment]
Oh my bad. I thought animeclick.it was a website where you can watch anime. I unfortunately wouldn’t be able to say exactly how to implement your own Anime Listing Service. Hopefully, marcus can explain. @SuperMarcus

**Comment by SuperMarcus** [comment]
If you're thinking about implementing your own listing service, take a look at the `ListingService` protocol and the `BaseListingService` class.

Basically you use the following getters to mark the capabilities of the service:

```Swift
var isCapableOfListingAnimeInformation: Bool { get }
var isCapableOfPersistingAnimeState: Bool { get }
var isCapableOfRetrievingAnimeState: Bool { get }
```

And the following method to map an `AnimeLink` to a `ListingAnimeReference`:

```Swift
func reference(from link: AnimeLink) -> NineAnimatorPromise<ListingAnimeReference>
```

And the following to retrieve the `ListingAnimeInformation` for a `ListingAnimeReference`:

```Swift
func listingAnime(from reference: ListingAnimeReference) -> NineAnimatorPromise<ListingAnimeInformation>
```

If you're only implementing anime information, just make `isCapableOfListingAnimeInformation` return true and `isCapableOfPersistingAnimeState`, `isCapableOfRetrievingAnimeState` return false.

If you need something to reference to, take a look at Anilist's implementations.
