### ISSUE TITLE
Anime Lists not complete

### ISSUE THREAD

**Issue by itadreik4** [SuperMarcus/NineAnimator#9]
The "Completed" and "Planned" section does not pull the entire list of anime from Kitsu.io.

**Comment by SuperMarcus** [comment]
I believe this should be fixed by ac5c18cdf6a20f5dae789d5486047ad70c185d4e. A new version containing this fix will be released later this week.

**Comment by SuperMarcus** [comment]
Please check the latest release to see if this issue still exists.
