### ISSUE TITLE
[BUG] Text color not proper for dark interface

### ISSUE THREAD

**Issue by UnknownOutsider** [SuperMarcus/NineAnimator#92]
![1AA7AACC-FE4C-43DB-97BE-1F9602B884A6](https://user-images.githubusercontent.com/33533915/78732627-65729800-7943-11ea-9144-de897660f1be.jpeg)

I think the text indicated last watched episode on the recently watch anime should be brighter while on dark mode.

**Comment by uttiya10** [comment]
this might be a bug with your app, not a problem with the design, since the text appears white on my iphone. Can you please join the discord so we can discuss further

**Comment by uttiya10** [comment]
Heres the discord link: https://discord.gg/dzTVzeW

@UnknownOutsider
