### ISSUE TITLE
[Feature Request] Anime list "View Episodes" button and source preferred language

### ISSUE THREAD

**Issue by Raffa2001** [SuperMarcus/NineAnimator#93]
So if I press on the homepage on “Kami no tou” and after view episodes, no matching but if I search “Tower of God” English name he find the anime(on the anime unity Italian source)

**Comment by uttiya10** [comment]
This doesn’t seem like a bug, since NineAnimator is simply searching up the Japanese name on animeunity. However, animeunity uses English names.

@SuperMarcus However, he is a feature request that might fix this problem:
MAL provides alternative names for an anime, however NineAnimator only searches up the main name. Instead, NineAnimator should search up the alternative names incase the main name doesn’t work.

**Comment by Raffa2001** [comment]
Should be add the search in the same moment with the English name

**Comment by SuperMarcus** [comment]
I can add an option in preferences to make the app search in certain languages.

**Comment by uttiya10** [comment]
Wouldn’t it be better to have the anime language defined in the sources? From what i know, 9anime always uses english titles, 4anime always uses Japanese, etc?.

**Comment by Raffa2001** [comment]
> This doesn’t seem like a bug, since NineAnimator is simply searching up the Japanese name on animeunity. However, animeunity uses English names.
> 
> 
> 
> @SuperMarcus However, he is a feature request that might fix this problem:
> 
> MAL provides alternative names for an anime, however NineAnimator only searches up the main name. Instead, NineAnimator should search up the alternative names incase the main name doesn’t work.

Yeah that is what I was trying to say

**Comment by SuperMarcus** [comment]
> Wouldn’t it be better to have the anime language defined in the sources? From what i know, 9anime always uses english titles, 4anime always uses Japanese, etc?

That's a good point. I'll start implementing it this way then.

**Comment by Raffa2001** [comment]
> > Wouldn’t it be better to have the anime language defined in the sources? From what i know, 9anime always uses english titles, 4anime always uses Japanese, etc?
> 
> 
> 
> That's a good point. I'll start implementing it this way then.

Sorry Marcus, this is the second feature request that I open 😅

**Comment by SuperMarcus** [comment]
> Sorry Marcus, this is the second feature request that I open 😅

Don't be sorry! You are welcomed to open feature requests at any time.

**Comment by SuperMarcus** [comment]
Here's what I found so far. Check me on this:

- 9anime - English
- ~~masterani.me~~
- gogoanime - English
- twist.moe - Romaji
- ~~wonderfulsubs~~
- animeultima - Romaji
- kissanime - Romaji
- animekisa - English
- 4anime - Romaji
- animedao - English
- animeunity - English

**Comment by uttiya10** [comment]
Gogoanime.tv seems to use Romaji
Kissanime.ru seems to use English

**Comment by uttiya10** [comment]
Hmm, seems like some websites are very consistent (9anime) while others are not (gogoanime). I had never noticed this since i dont use these website that often

**Comment by uttiya10** [comment]
Update: Seems like anime that DO NOT have english titles, are being shown as Romaji. The default however seems to be English (for gogoanime)

**Comment by SuperMarcus** [comment]
> Hmm, seems like some websites are very consistent (9anime) while others are not (gogoanime)...

You're absolutely correct. But I've also noticed for those who are less consistent, both Romaji and English searches works. Also, 9anime can have different titles between the titles from their search page and that from the playback page.

**Comment by uttiya10** [comment]
>  Also, 9anime can have different titles between the titles from their search page and that from the playback page.

Yeah, I experienced this before. I also did testing, it seems that searching english and Romaji works on gogoanime and kissanime, like you said. 
So it looks like everything in your list is fine, ill update you if i find anything

**Comment by SuperMarcus** [comment]
One thing I would take note is that Anilist sometimes put Romaji and English together. So, for example, the Tower of God is listed as `Kami no Tou: Tower of Gods` for the Romaji variant, which will still yield a no result in 4anime.

**Comment by uttiya10** [comment]
Haven’t checked the api, but isnt it possible to just request only english/romaji name?

**Comment by SuperMarcus** [comment]
> Haven’t checked the api, but isnt it possible to just request only english/romaji name? 

Yes. `Kami no Tou: Tower of God` is the Romaji name that Anilist returns.

**Comment by uttiya10** [comment]
For the romaji names that have english in it, is the format always:
`Romaji:English`

**Comment by uttiya10** [comment]
As long as Anilist uses `Romaji: English` format of writing their titles (when they combine the languages), then isn't it possible to check if the string contains the English name, and remove it before searching?
```swift
let fakeRomaji = "Kami no Tou: Tower of God"
if fakeRomaji.hasSuffix(": Tower of God") { // use english name provided by Anilist Api
    let trueRomaji = fakeRomaji.replacingOccurrences(of: ": Tower of God", with: "")
    print(trueRomaji)
}
```
