### ISSUE TITLE
[BUG] Chromecast Menu crashes when selecting device

### ISSUE THREAD

**Issue by uttiya10** [SuperMarcus/NineAnimator#97]
Discord user: Laniax #2980
Crash Logs:
[NineAnimator-2020-04-17-201741.ips.beta.zip](https://github.com/SuperMarcus/NineAnimator/files/4494864/NineAnimator-2020-04-17-201741.ips.beta.zip)
P.S. I hate that github doesnt accept .beta files.

**Comment by SuperMarcus** [comment]
Commit 6851ea4 should have addressed this issue partially. We need some more testings before closing this issue.
